### ISSUE TITLE
PCR.DigestAlg doesnt seem to be reliable

### ISSUE THREAD

**Issue by twitchy-jsonp** [google/go-attestation#116]
Its set on SHA256 for some SHA1 PCRs ive had coming from the simulator. Need to investigate.

**Comment by mjg59** [comment]
https://github.com/google/go-attestation/pull/152 - even if we're selecting SHA1 PCRs, the algorithm used on the signature is determined by the AK so could (and should!) be something other than SHA1.

**Comment by twitchy-jsonp** [comment]
This was fixed by #152.
