### ISSUE TITLE
Make platformTPM public for downstream testing

### ISSUE THREAD

**Issue by caleblloyd** [google/go-attestation#156]
I am contributing to a downstream project, [spire-tpm-plugin](https://github.com/bloomberg/spire-tpm-plugin), and would like to be able to test using the TPM simulator like this project does:

https://github.com/google/go-attestation/blob/25ce56400c9ff0a90a3f8b3eb47bf1698fe9319a/attest/attest_simulated_tpm20_test.go#L30-L42

The issue I'm running into is that `platformTPM` is a private struct, so I am unable to "fake" the TPM in downstream testing

**Comment by caleblloyd** [comment]
I believe that `TPM.tpm` would also need to be made public, as would all of `platformTPM`'s members

Or the package could provide a helper function of some sort to return a simulated TPM?

**Comment by ericchiang** [comment]
I don't think we'd want to expose platformTPM. Maybe an option to OpenConfig to use an in-memory simulator instead?

**Comment by twitchy-jsonp** [comment]
I'm hesitant to make `github.com/google/go-tpm-tools/simulator` a non-test build dependency, to avoid complicating the cgo story.

What if instead we allowed the caller to provide a TPM data channel, which would be used by `go-tpm` as normal?

Something like

```go

type OpenConfig struct {
  ...
  CommandChannel io.ReadWriteCloser
}
```

And possibly a new type for `CommandChannel`, in case we need methods in the future.

**Comment by josephlr** [comment]
> What if instead we allowed the caller to provide a TPM data channel, which would be used by `go-tpm` as normal?

+1 to this idea. This is what we do for testing w/ `gotpm` and `go-tpm-tools`. You definitely want to avoid unconditionally linking in the simulator (it's big, complicated, requires CGo, and needs OpenSSL to be installed).

**Comment by ericchiang** [comment]
@caleblloyd want to send a PR?

**Comment by caleblloyd** [comment]
Sure I will give it a shot!

**Comment by caleblloyd** [comment]
I have been digging through the code for a few hours and here's what I've found:

1. Supporting `CommandChannel` for TPM2 on Linux - easy fix as `CommandChannel` can set `platformTPM.rwc` 
2. Supporting `CommandChannel` for TPM2 on Linux and Windows - more difficult as Windows `platformTPM` does not have a `rwc`.  Could Windows TPM2 share logic with Linux TPM2 by simply calling `t.pcp.TPMCommandInterface()` and running all commands on a generic TPM2 object that takes `io.ReadWriteCloser`?
3. Supporting `CommandChannel` for TPM1.2 and TPM2 - very difficult, there are commands in the TPM1.2 logic on Linux and Windows that do not run over `io.ReadWriteCloser`, and refactoring those is outside my current depth of knowledge on TPM

So I could implement (1) no problem, (2) with a little guidance, but would need to defer to someone with more subject matter expertise if (3) is the desired end state

**Comment by caleblloyd** [comment]
It appears that the simulator test already assumes Linux, since it uses the Linux `platformTPM`.  So solution (1) would maintain that functionality.

**Comment by twitchy-jsonp** [comment]
Ahh whelp, forgot about PCP on windows. I guess that means we can't use `CommandChannel` for Windows, unless we move to a TBS-only windows implementation.

That said, its clear it would still be useful to be able to inject a TPM 2.0 command channel for the common case, or integration testing.

> Could Windows TPM2 share logic with Linux TPM2 by simply calling `t.pcp.TPMCommandInterface()` and running all commands on a generic TPM2 object that takes `io.ReadWriteCloser`

We wanted to do this originally, but on Windows configuration of the authorization values for the Endorsement hierarchy mean this isnt possible. If support for delegated authorization was implemented in `go-tpm`, we could implement something that only used the rwc, but it would not look much like the Linux implementation.

> So I could implement (1) no problem, (2) with a little guidance, but would need to defer to someone with more subject matter expertise if (3) is the desired end state

I think (1) is way to go here imho.

**Comment by twitchy-jsonp** [comment]
Does #161 fit your needs?

**Comment by caleblloyd** [comment]
Yes, it works great - thank you @twitchy-jsonp and @ericchiang !
