### ISSUE TITLE
Use build tags to allow building without tspi

### ISSUE THREAD

**Issue by josephlr** [google/go-attestation#163]
Right now, a user of go-attestation must download and install libtspi-dev even if they only wish to use TPM2 (such as with GCE). This can be problematic as this library is not distributed with all Linux distros.

Go supports [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) to allow for conditional compilation. Similar to how we don't require tspi on Windows builds, we could use a `notspi` build constraint to allow:
```bash
go build -notspi windows ./attest/attest-tool
```
to build without tspi.

We could also invert the semantics, having the `tspi` build flag _enable_ support for TPM 1.2 on Linux, depending on what we want to be the default.

**Comment by vinaykotak** [comment]
@josephlr Do you have an ETA on when the PR for this issue is expected to merge?
