### ISSUE TITLE
Request to tag the latest version: (0.2.1?)

### ISSUE THREAD

**Issue by neeki-hushyar** [google/go-attestation#183]

**Comment by aditya4k** [comment]
Looks like the latest code is based on go-tpm v0.3.1 while the last released tag is based on github.com/google/go-tpm v0.2.1-0.20191015210219-431489f43254. This causes error:
```
# github.com/google/go-attestation/attest
vendor/github.com/google/go-attestation/attest/tpm_linux.go:301:152: cannot use &tix (type *tpm2.Ticket) as type tpm2.Ticket in argument to tpm2.CertifyCreation
```

@ericchiang  could you please check?

**Comment by brandonweeks** [comment]
https://github.com/google/go-attestation/releases/tag/v0.2.1
