### ISSUE TITLE
Instructions on how to generate CSR

### ISSUE THREAD

**Issue by feeltheajf** [google/go-attestation#200]
Hi! Really appreciate your hard work on this project guys. I have a question regarding post-activation steps

> the server records the AK and EK association and allows the client to use its AK as a credential (e.g. by issuing it a client certificate).

My understanding is that client should also send a CSR for server to issue certificate. I've spent some time trying to find information on how to create CSR using generated AK, but did not succeed. Can you please give me any links/instructions to point me in the right direction?

**Comment by ericchiang** [comment]
Issuing certificates doesn't necessarily need to use PKCS #10 CSR structs, that's just one way for a client to say "here's a public key and some requested DNS names, please issue a certificate". Either way the CA needs to use other information to verify the client isn't lying and actually control the DNS names/key.

I wrote a bunch about attestation and that kind of thing here: https://ericchiang.github.io/post/tpm-keys/

If the CA already knows a client has possession of a private key, then it largely can just issue it a certificate. That could be a CSR struct, but it also could be just a regular REST or gRPC endpoint (e.g. look at the ACME protocol).

**Comment by feeltheajf** [comment]
Thanks for clarification, @ericchiang! Will look into it
