### ISSUE TITLE
Quote of set of PCRs

### ISSUE THREAD

**Issue by 538Michael** [google/go-attestation#220]
Hello, I'm working with your lib and I wonder if you plan to make a function to make the quote using a set of pcrs. Because I've studied your lib and I saw you only give me a way to make a quote using all pcrs.

**Comment by ericchiang** [comment]
We don't have a plan to expose an API. Do you have a use case in mind? Generally you can just quote all the PCRs then inspect the ones you care about.

**Comment by 538Michael** [comment]
Yeah, that was my initial idea, I just thought I could somehow use only the ones I wanted sisnce the beginning, but well, that's no problem, it will make my life easier. I have another question, is there a way to get the pcrs values from the signed quote (server side)?
