### ISSUE TITLE
Verifying the Quote

### ISSUE THREAD

**Issue by 538Michael** [google/go-attestation#225]
Hello, a couple days ago I came here to talk about a question of retrieving the PCRs values from the Quote and I got Verify method as answer, I've studied about this method and as I see, it compares all 24 PCRs values, I would like to know if I could select which PCRs I want to be compared. For example, In my problem I only need PCRs 2, 4, 5, 6 and 9.

**Comment by ericchiang** [comment]
There's no mechanism to do this today. Is this a requirement? Is it problematic that you also compare all 24 PCRs?

**Comment by 538Michael** [comment]
It's because in my problem we don't need to compare some PCRs, whose values change from time to time, we just want to compare a minimum number necessary for our attestation. Do you plan to implement it at some point?

**Comment by ericchiang** [comment]
We don't plan on implementing it, though if you want to propose an API change we'd be happy to review.

Generally, you should be fine to just look at a subset of the PCRs even if you compare all 24.
