### ISSUE TITLE
Importing the library locally

### ISSUE THREAD

**Issue by 538Michael** [google/go-attestation#229]
Hello, I downloaded the library and tried to import it locally from my pc, but it returns me many errors when executing, any reason for that?
Here's a screenshot of the errors: [https://imgur.com/a/WsvStLC](https://imgur.com/a/WsvStLC)

**Comment by josephlr** [comment]
What does your importing code and go modules look like?

With Golang, if you want your local application to depend on a local copy of a dependancy, your application code imports the dependancy like normal (i.e. using the github path). Then, you use a `replace` directive in your application's `go.mod` file.

The official Golang documentation explains the process: https://golang.org/ref/mod#go-mod-file-replace

**Comment by 538Michael** [comment]
It used to be 

```
package main
import (
	"bytes"
	"crypto/ecdsa"
	"crypto/rsa"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"github.com/google/certificate-transparency-go/x509"
	"github.com/google/go-attestation/attest"
	"time"
)
```

I just replaced 

> "github.com/google/go-attestation/attest"

by the local import

> "../go-attestation-master/attest"

**Comment by josephlr** [comment]
Ya you will need to change your go.mod to point at your local copy rather than changing the source code (see above comment). This doesn't seem like a go-attestation specific problem
