### ISSUE TITLE
Pi Build

### ISSUE THREAD

**Issue by RRToast** [google/go-attestation#230]
I'm trying a simple test program on my Pi and i run into this issue during building:

```
# github.com/google/go-tspi/tspi
../go/pkg/mod/github.com/google/go-tspi@v0.2.1-0.20190423175329-115dea689aad/tspi/tpm.go:92:13: type [1073741824]_Ctype_struct_tdTSS_PCR_EVENT larger than address space
../go/pkg/mod/github.com/google/go-tspi@v0.2.1-0.20190423175329-115dea689aad/tspi/tpm.go:92:13: type [1073741824]_Ctype_struct_tdTSS_PCR_EVENT too large
```

if i understood this error correctly this is linked to 
![image](https://user-images.githubusercontent.com/43878153/124072801-8ee47b80-da41-11eb-9563-5a4614165f9b.png)
in attest/tpm.go. Is there a common or known workaround for this issue?

Specs:
Pi4 (raspdebian 10.9)
go1.16.5 linux/arm

**Comment by ericchiang** [comment]
I think the bug is in a dependency not in go-attestation

https://github.com/google/go-tspi/blob/d3ac1f5d1244a2f575ccf1e428b500fe696464ea/tspi/tpm.go#L92
