### ISSUE TITLE
Revert of tspi build tag

### ISSUE THREAD

**Issue by Foxboron** [google/go-attestation#255]
Yo,

It seems the changes made to the buildflag to disable tspi was reverted without any explicit comment why?

Introduction: https://github.com/google/go-attestation/pull/237

Revert: https://github.com/google/go-attestation/commit/be496f11497f3382fed7e66c6170b1bba46f369a

Would i be possible to partially revert this revert or is there any reason for this change?

**Comment by ericchiang** [comment]
@brandonweeks
