### ISSUE TITLE
Cannot set key attributes in NewKey and RSA template doesnt allow for "decrypt" - mTLS in Chrome not possible

### ISSUE THREAD

**Issue by kuhlmannmarkus** [google/go-attestation#272]
Hi,

we are using a key generated with `NewKey` in combination with https://github.com/tpm2-software/tpm2-pkcs11 to achieve mutual TLS authentication against some web applications in the browser. This does not directly work in Chrome, because the template for RSA keys is missing the `decrypt` flag. Adding the flag in the template leads to success. I want to understand what exactly is the reason to not include the flag for application keys. Would it be possible to set the key attributes at run time? I cannot find a method to do so.

Cheers
Markus

**Comment by josephlr** [comment]
I was under the impression that mTLS 1.3 only needed signing keys. What would asymmetric decryption keys even be used for? I was under the impression that the only encryption/decryption in TLS 1.3 was symmetric encryption.

We have used signing-only TPM keys to establish a TLS session, but we used Go's TLS stack rather that directly interfacing with Chrome.

**Comment by josephlr** [comment]
If you want to specify and entire template to create a Key, maybe look at: https://pkg.go.dev/github.com/google/go-tpm-tools/client#NewKey
