### ISSUE TITLE
A question about EK,SRK

### ISSUE THREAD

**Issue by shuk777** [google/go-attestation#282]

**Comment by shuk777** [comment]
Hi,there.

I'm currently using your repo as a start for TPM research. I've noticed that in your code it seems that the AK is generated from SRK. However, the official documents I've been reading say that the AKs should be generated from EK. And I'm wondering how would you verify the EK and AK comes from the same TPM since the EK and SRK belongs to different hierarchies. 

In addition, thanks to your repo, it really helps me a lot in understanding how to interact with TPM2 APIs

Best regards

**Comment by ericchiang** [comment]
Hey!

The AIK is generally attested by the EK but lives under the storage hierarchy.

* https://trustedcomputinggroup.org/wp-content/uploads/IWG_CMC_Profile_Cert_Enrollment_v1_r7.pdf#page=14
* https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf#page=103
* https://ericchiang.github.io/post/tpm-keys/#key-hierarchies

**Comment by twitchyliquid64** [comment]
One more thing about why its under the storage hierarchy: The storage hierarchy is meant to match the lifecycle of a use of a device (ie: it ends when the device goes to another user and gets re-imaged), whereas the endorsement hierarchy matches the life of the entire device as a whole. Given typical use of this library (establishing the identity of a device then using an AK to attest other credentials or platform state), it doesn't make a lot of sense for us to jump through the extra hoops of EK authorization when the storage hierarchy lifecycle already matches the lifetime of the state files we manage on disk (which would only get blown away on a reimage anyway, negating the benefit of the endorsement hierarchy).

There are other practical considerations too: This is how windows does it for example, so we have to follow suit if we want to use the PCP APIs.

**Comment by shuk777** [comment]
Wow, thanks for your explanations and documents.

**Comment by ericchiang** [comment]
Happy to help! Going to mark this as closed for now since it seems like this has been answered.
