### ISSUE TITLE
Wrong decoding of ints in win_events.go

### ISSUE THREAD

**Issue by hansinator** [google/go-attestation#289]
https://github.com/google/go-attestation/blob/master/attest/win_events.go#L397

The function above decodes a uvarint, however, none of the values read are encoded as uvarint. It works for values < 255 but reads wrong values otherwise.

Have a look at this code here:
https://github.com/microsoft/TSS.MSR/blob/master/PCPTool.v11/exe/Support.cpp

MS's code shows the values are either fixed uint64 or uint32.

f.e.
https://github.com/microsoft/TSS.MSR/blob/master/PCPTool.v11/exe/Support.cpp#L709
https://github.com/microsoft/TSS.MSR/blob/master/PCPTool.v11/exe/Support.cpp#L561
https://github.com/microsoft/TSS.MSR/blob/master/PCPTool.v11/exe/Support.cpp#L571
https://github.com/microsoft/TSS.MSR/blob/master/PCPTool.v11/exe/Support.cpp#L722

I've fixed it in my fork and could open a PR if wanted.

**Comment by ericchiang** [comment]
Happy to take fixes, thanks!
