### ISSUE TITLE
Handle "AttestedCertifyInfo" in ActivationParameter checks for TPM2.0 Challenges

### ISSUE THREAD

**Issue by juanvallejo** [google/go-attestation#320]
ActivationParameters currently only supports handling the `tpm2.TagAttestCreation`. Support for `tpm2.TagAttestCertify` is currently missing.

The context behind this change is to add the ability to create an Activation Challenge for a TPM, using AttestedCertify info instead of the currently-supported AttestedCreation info.

None of the current checks against ActivationParameters would change as a result.
The main consequence of this would be that the AIK value used in generating an activation challenge would be [derived from the name digest of an AttesttedCertify structure instead of an AttestedCreation structure](https://github.com/google/go-attestation/blob/master/attest/activation.go#LL242C50-L242C86).

cc @ericchiang

**Comment by ericchiang** [comment]
Does this require a change to the AK the way we generate the AK, or is this specifically only related to the challenge?

Would that look like adding a field to opt into attest certify rather than attest creation? E.g. if we had something like

```go
type AttestationType int

const (
    AttestCreation AttestationType = iota // Default value
    AttestCertify
)
```

Then let you specify that field in ActivationParameters and CertificationParameters, would that work?

https://pkg.go.dev/github.com/google/go-attestation/attest#ActivationParameters
https://pkg.go.dev/github.com/google/go-attestation/attest#CertificationParameters

**Comment by juanvallejo** [comment]
> Does this require a change to the AK the way we generate the AK, or is this specifically only related to the challenge?
This is only specifically to the challenge.

> Would that look like adding a field to opt into attest certify rather than attest creation? E.g. if we had something like
When we parse attestation data using [tpm2.DecodeAttestationData](https://github.com/google/go-tpm/blob/master/tpm2/structures.go#L667), the bytes we initially receive for attestation data should already have a [tag that matches one of the ones already present in the tpm2 library](https://github.com/google/go-tpm/blob/master/tpm2/constants.go#L402) to determine whether we're dealing with AttestedCertify data or AttestedCreation data. So no further changes needed, especially given that the library already recognizes both tag-types we intend to handle here.

**Comment by ericchiang** [comment]
Cool. I will note that one of the explicit goals of this package is to avoid the need to use go-tpm2 directly. So if we add support for verifying a particular challenge type, we should also add support for generating it.

I don't think it makes sense for us to only support verification.
