### ISSUE TITLE
Make AttestationParameters.CreateData an optional field

### ISSUE THREAD

**Issue by juanvallejo** [google/go-attestation#321]
We currently require the `CreateData` field to be specified when [generating a TPM2.0 activation challenge](https://github.com/google/go-attestation/blob/master/attest/activation.go#L129).

The purpose of this field is currently to:
1. [Make sure the bytes provided unmarshal cleanly onto a `CreationData` struct](https://github.com/google/go-attestation/blob/master/attest/activation.go#L100).
2. [Check that the Opaque Digest of an `AttestedCreationInfo` struct matches the hashsum of the provided `CreateData`](https://github.com/google/go-attestation/blob/master/attest/activation.go#L130).

This issue proposes making this field an optional check performed only when provided, as part of generating an activation challenge for a TPM 2.0.

cc @ericchiang

**Comment by ericchiang** [comment]
So the proposal is essentially not to check anything related to CreationData if it's not provided.

That sounds reasonable, but when and why would someone ever skip this check? I'm trying to figure out how we'd update the API documentation

**Comment by juanvallejo** [comment]
> So the proposal is essentially not to check anything related to CreationData if it's not provided.

That's correct, please correct me here, but based on my current understanding of the spec, "CreationData" is coupled with `AttestedCreationData`. The struct [backing `AttestedCertifyInfo`](https://github.com/google/go-tpm/blob/master/tpm2/structures.go#L789) does not contain an `OpaqueDigest` field to compare against CreationData, but the struct backing AttestedCreationInfo does contain such a field](https://github.com/google/go-tpm/blob/master/tpm2/structures.go#L750), which is already used in the library [for its intended check](https://github.com/google/go-attestation/blob/master/attest/activation.go#L130).

**Comment by juanvallejo** [comment]
Closing this issue as I have since realized that `CertificationParameters` is almost symmetrical to `AttestationParameters` and already has this field as optional.
