### ISSUE TITLE
attest-tool: listing EKs fails on Windows VM

### ISSUE THREAD

**Issue by ericchiang** [google/go-attestation#74]
attest-tool isn't able to list EKs on a shielded Windows VM. Figure out if this is an issue with attest-tool or the attest package.

**Comment by twitchy-jsonp** [comment]
`tpm.EKs()` on windows only scans for EK certificates, logic to read the EK key if no certificate is found has not been implemented.

So there are two pieces here:
 - The VM does not have an EK certificate
 - `EKs()` does not fallback to reading just the EK if no certificate is present.

**Comment by ericchiang** [comment]
tpm.EKs should definitely return an error if it would return a slice of zero length.

I think go-attestation should support EKs without certificates, particularly if it helps with GCP support. That might be a different issue though :)
