### ISSUE TITLE
attest: figure out hashing algorithm strategy

### ISSUE THREAD

**Issue by ericchiang** [google/go-attestation#75]
This is a super-set of https://github.com/google/go-attestation/issues/72

It's currently unclear when a user needs to provide SHA1 or SHA256, or when we can infer it from other data. There are several places where we need a hash:

* To determine the signature algorithm on the quote. Is this always inferred from the TPM public blob?
* To determine which quote we should send to the server. TPM 2.0 doesn't guarantee that the eventlog will correctly contain SHA256, even if the PCRs store SHA256 values. Should this be determined by inspecting the measurement log?
* It's unclear why AIK.Quote() requires a HashAlg, or how this should be filled.

For now, I propose we modify the MeasurementLog signature to return the hash:

```
func (t *TPM) MeasurementLog() ([]byte, HashAlg, error)
```

And the PCRs call to take a hash:

```
func (t *TPM) PCRs(alg HashAlg) ([]PCR, error)
```

Users would then do something like

```
rawLog, alg, err := tpm.MeasurementLog()
if err != nil {
    // ...
}
pcrs, err := tpm.PCRs(alg)
```

**Comment by twitchy-jsonp** [comment]
According to https://www.trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf, section 18.4:

The provided algorithm is used to digest the PCRs into a single value for the signature. In theory, TPM 2 devices will always support SHA256, but iirc I had some issues getting SHA256 quotes working for non-sha256 event logs (but my memory is flaky).

**Comment by ericchiang** [comment]
brandonweeks@ has been volunteered to take this
