### ISSUE TITLE
attest: Allow verification of quote without a corresponding event log

### ISSUE THREAD

**Issue by twitchy-jsonp** [google/go-attestation#85]
Users may choose to use Quote() to challenge the presence of an AIK, by quoting over PCRs and providing a nonce. In this case, there is no event log (and there may be none present), but we still want to be able to verify the quote.

Currently, the API for verifying a quote is coupled into event log verification (users must call `EventLog{}.Validate()`, which will fail if they do not provide an event log).

Proposal 1: Add a `Verify(aik, nonce, pcrs)` method directly on `Quote`
Proposal 2: Make it legal to call `Validate` on `EventLog` where no event log is present.

WDYT @ericchiang ?

**Comment by ericchiang** [comment]
Closed by #87
